server:
  port: 3001
spring:
  application:
    name: api-gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/

zuul:
  add-host-header: true
  sensitive-headers:
  host:
    connect-timeout-millis: 6000
    socket-timeout-millis: 6000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeout-in-milliseconds: 6000







