server:
  port: 2003
spring:
  datasource:
    transaction:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://aws-db.cwgnhujbnrwi.ap-northeast-1.rds.amazonaws.com:3306/gdpj?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: zfm123456
      initial-size: 2
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      filters: stat,wall
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  application:
    name: transaction-module

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/

logging:
  level:
    indi.fimi.gdpj.transaction.repository: debug


